apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: threenginx
spec:
  replicas: 4
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  template:
    metadata:
      labels:
        team: green
        type: npc3
    spec:
      containers:
        - image: tourna/nginx:v3
          name: threenginx
