apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpdnpc
spec:
  replicas: 4
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  template:
    metadata:
      labels:
        team: red
        type: npc2
    spec:
      containers:
        - image: tourna/httpd:v2
          name: httpd
