apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginxnpc
spec:
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  template:
    metadata:
      labels:
        team: green
        type: npc
    spec:
      containers:
        - image: tourna/nginx:v1
          name: nginx
