apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubecon
spec:
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  template:
    metadata:
      labels:
        team: green
        type: npc
    spec:
      containers:
        - image: gluobe/garrys-pod:v1
          name: garrys-pod
